### PR TITLE
Add entrypoints to requirements

### PR DESCRIPTION
**Pull request by kevin-bates**
This updates the conda recipe to include `entrypoints` as a dependency as that is new in the 7.0 release.  I didn't have permission to push directly, thus this PR.

Question: as best as I can determine (poking around other feedstocks), it seems the `entry_points` entries in `meta.yml` only pertain to `console_scripts`.  Is there a way (and is it necessary) to add entries for "custom" entrypoints (e.g., like [`jupyter_client.kernel_provisioners`](https://github.com/jupyter/jupyter_client/blob/be67c654ecd15f7ef6ca0db557f2d47f5b14e8d8/setup.py#L68))?

cc: @bollwyvl, @carreau, @davidbrochart

### CODE REVIEW

**Comment by Carreau** [comment]
I'm not sure on entrypoints, I've found [this](https://conda-forge.org/docs/maintainer/knowledge_base.html):

> Only console_scripts entry points have to be listed in meta.yaml. Other entry points do not conflict with noarch and therefore do not require extra treatment.

I don't have the ability to merge to this repo either, I think we should just make a PR against the main repo.

**Comment by Carreau** [comment]
> I think we should just make a PR against the main repo.

And bump the build number.

**Comment by kevin-bates** [comment]
@Carreau - thank you for your response and finding the entrypoint information.  I looked at another repo that defines custom entrypoints and see that it only specifies `console_scripts` as well - so at least the information is consistent.  

I'm a noob when it comes to conda-forge maintainer duties.  When you say "make a PR against the main repo" are you referring to conda-forge/jupyter_client-feedstock (and similar to what I've done here)?

and
> And bump the build number.

Does that mean to set the build number to `1` in the [meta.yml recipe file](https://github.com/regro-cf-autotick-bot/jupyter_client-feedstock/blob/66b0ecc6d96dffffd6939cdbb33b7651d85d2c09/recipe/meta.yaml#L13)?

**Comment by Carreau** [comment]
> I'm a noob when it comes to conda-forge maintainer duties. When you say "make a PR against the main repo" are you referring to conda-forge/jupyter_client-feedstock (and similar to what I've done here)?

Yes, 

> Does that mean to set the build number to `1` in the [meta.yml recipe file](https://github.com/regro-cf-autotick-bot/jupyter_client-feedstock/blob/66b0ecc6d96dffffd6939cdbb33b7651d85d2c09/recipe/meta.yaml#L13)?

And I believe yes.

I'm not too familiar with conda-forge these days, mostly all is automatic from my point of view with Nick Bollweg reacting and fixing/merging stuff before I even got notifications.

**Comment by jakirkham** [comment]
Also we want to send this PR to this repo ( https://github.com/conda-forge/jupyter_client-feedstock )

**Comment by kevin-bates** [comment]
I'm going to close this PR since 7.0.0 is already outdated.  A [7.0.1 PR was merged](https://github.com/conda-forge/jupyter_client-feedstock/pull/58), but is incorrect.  Since I'm not permitted to push to the `regro-cf-autotick-bot` repo, how does one go about generating a proper PR against `conda-forge` directly?

Can someone provide me with the correct privs to push to `regro-cf-autotick-bot` branches?

**Comment by davidbrochart** [comment]
I opened https://github.com/conda-forge/jupyter_client-feedstock/pull/59 to add you as a maintainer (please comment there saying that you agree).

**Pull request closed without merging**
